- name: Check dependencies
  import_tasks: check-dependencies.yml

- name: Build Image
  import_tasks: image-build.yml

- name: Tag Image
  import_tasks: image-tag.yml

- name: Push Image
  import_tasks: image-push.yml

- name: Transfer Image
  import_tasks: image-transfer.yml